// <auto-generated />
using System;
using Gestion_Recommandation.API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Gestion_Recommandation.API.Migrations.AppDb
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20211024142959_createTblRecommandation")]
    partial class createTblRecommandation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Gestion_Recommandation.Shared.Models.Recommandations", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateReference")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeLaPart")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ID_User")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdentityRecommandation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InstructionDRH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroReference")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Source")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Recommandations");
                });
#pragma warning restore 612, 618
        }
    }
}
